

export const BLOOD_GROUPS = [
  'A+', 'A-', 'B+', 'B-', 'AB+', 'AB-', 'O+', 'O-'
];

export const EMERGENCY_NUMBERS = {
  POLICE: '100', // Example: India/Generic
  FIRE: '101',
  AMBULANCE: '102',
  GENERAL: '911' // or 112
};

export const USE_MOCK_FIREBASE = false; 

export const DEFAULT_SUGGESTIONS = [
  "How to do CPR on an infant?",
  "Treating a severe burn",
  "Choking first aid for adults",
  "Symptoms of heat stroke"
];

export const SUPPORTED_LANGUAGES = [
  { code: 'en-US', name: 'English' },
  { code: 'te-IN', name: 'తెలుగు' },
  { code: 'hi-IN', name: 'हिन्दी' },
  { code: 'ta-IN', name: 'தமிழ்' }
];

export const TRANSLATIONS: Record<string, Record<string, string>> = {
  'en-US': {
    appTitle: "LifeGuard AI",
    home: "Home",
    firstAid: "First Aid",
    nearby: "Nearby",
    profile: "Profile",
    welcome: "Hello",
    emergencyMode: "Emergency Mode Active. Help is just a tap away.",
    blood: "Blood",
    contact: "Contact",
    sosTitle: "Emergency SOS",
    ambulance: "Ambulance",
    police: "Police",
    fire: "Fire",
    family: "Family",
    quickAssist: "Quick Assistance",
    firstAidTitle: "First Aid AI",
    firstAidDesc: "Get instant guidance for CPR, burns, and cuts.",
    findHospitals: "Find Hospitals",
    findHospitalsDesc: "Locate nearest medical centers instantly.",
    chatPlaceholder: "Describe the emergency...",
    listen: "Listen",
    stop: "Stop",
    send: "Send",
    medicalId: "Medical ID",
    save: "Save",
    edit: "Edit",
    medicalCond: "Medical Conditions",
    currentLoc: "Current Location",
    update: "Update",
    updating: "Updating...",
    settings: "Settings",
    language: "Language",
    privacy: "Privacy Policy",
    mapApp: "Use Google Maps App",
    navMap: "Get turn-by-turn navigation",
    open: "Open",
    getDir: "Get Directions",
    locating: "Locating...",
    signIn: "Sign In",
    createAccount: "Create Account",
    sources: "Sources found:",
    nearbyCenters: "Nearby Medical Centers",
    chatHistory: "Chat History",
    noHistory: "No chat history available.",
    yourQuery: "You asked",
    dropPin: "Dropped Pin",
    navHere: "Navigate Here",
    tapMap: "Tap map to drop pin"
  },
  'te-IN': {
    appTitle: "LifeGuard AI",
    home: "హోమ్",
    firstAid: "ప్రథమ చికిత్స",
    nearby: "దగ్గరలో",
    profile: "ప్రొఫైల్",
    welcome: "నమస్కారం",
    emergencyMode: "ఎమర్జెన్సీ మోడ్ యాక్టివ్. సహాయం ఒక్క ట్యాప్ దూరంలో ఉంది.",
    blood: "రక్తం",
    contact: "కాంటాక్ట్",
    sosTitle: "ఎమర్జెన్సీ SOS",
    ambulance: "అంబులెన్స్",
    police: "పోలీసు",
    fire: "ఫైర్",
    family: "కుటుంబం",
    quickAssist: "త్వరిత సహాయం",
    firstAidTitle: "ఫస్ట్ ఎయిడ్ AI",
    firstAidDesc: "CPR, కాలిన గాయాలు మరియు కోతలకు తక్షణ సలహా పొందండి.",
    findHospitals: "ఆసుపత్రులను కనుగొనండి",
    findHospitalsDesc: "దగ్గరలోని వైద్య కేంద్రాలను తక్షణమే గుర్తించండి.",
    chatPlaceholder: "ఎమర్జెన్సీని వివరించండి...",
    listen: "వినండి",
    stop: "ఆపు",
    send: "పంపండి",
    medicalId: "మెడికల్ ID",
    save: "సేవ్ చేయి",
    edit: "ఎడిట్",
    medicalCond: "వైద్య పరిస్థితులు",
    currentLoc: "ప్రస్తుత లొకేషన్",
    update: "అప్‌డేట్",
    updating: "అప్‌డేట్ అవుతోంది...",
    settings: "సెట్టింగ్స్",
    language: "భాష",
    privacy: "గోప్యతా విధానం",
    mapApp: "Google Maps యాప్ వాడండి",
    navMap: "టర్న్-బై-టర్న్ నావిగేషన్ పొందండి",
    open: "ఓపెన్",
    getDir: "దిశలు",
    locating: "లొకేటింగ్...",
    signIn: "సైన్ ఇన్",
    createAccount: "ఖాతా సృష్టించండి",
    sources: "మూలాలు దొరికాయి:",
    nearbyCenters: "దగ్గర్లోని వైద్య కేంద్రాలు",
    chatHistory: "చాట్ చరిత్ర",
    noHistory: "చాట్ చరిత్ర అందుబాటులో లేదు.",
    yourQuery: "మీరు అడిగారు",
    dropPin: "పిన్ వేయబడింది",
    navHere: "ఇక్కడికి నావిగేట్ చేయండి",
    tapMap: "పిన్ వేయడానికి మ్యాప్‌పై నొక్కండి"
  },
  'hi-IN': {
    appTitle: "LifeGuard AI",
    home: "होम",
    firstAid: "प्राथमिक चिकित्सा",
    nearby: "पास में",
    profile: "प्रोफाइल",
    welcome: "नमस्ते",
    emergencyMode: "आपातकालीन मोड सक्रिय। मदद बस एक टैप दूर है।",
    blood: "रक्त",
    contact: "संपर्क",
    sosTitle: "आपातकालीन SOS",
    ambulance: "एम्बुलेंस",
    police: "पुलिस",
    fire: "दमकल",
    family: "परिवार",
    quickAssist: "त्वरित सहायता",
    firstAidTitle: "फर्स्ट एड AI",
    firstAidDesc: "CPR, जलन और चोट के लिए तुरंत मार्गदर्शन प्राप्त करें।",
    findHospitals: "अस्पताल खोजें",
    findHospitalsDesc: "तुरंत नजदीकी चिकित्सा केंद्र खोजें।",
    chatPlaceholder: "आपात स्थिति का वर्णन करें...",
    listen: "सुनें",
    stop: "रुकें",
    send: "भेजें",
    medicalId: "मेडिकल ID",
    save: "सहेजें",
    edit: "संपादित करें",
    medicalCond: "चिकित्सा स्थितियां",
    currentLoc: "वर्तमान स्थान",
    update: "अपडेट करें",
    updating: "अपडेट हो रहा है...",
    settings: "सेटिंग्स",
    language: "भाषा",
    privacy: "गोपनीयता नीति",
    mapApp: "Google मैप्स का उपयोग करें",
    navMap: "टर्न-बाय-टर्न नेविगेशन प्राप्त करें",
    open: "खोलें",
    getDir: "दिशा - निर्देश",
    locating: "खोज रहा है...",
    signIn: "साइन इन करें",
    createAccount: "खाता बनाएं",
    sources: "स्रोत मिले:",
    nearbyCenters: "निकटतम चिकित्सा केंद्र",
    chatHistory: "चैट इतिहास",
    noHistory: "कोई चैट इतिहास उपलब्ध नहीं है।",
    yourQuery: "आपने पूछा",
    dropPin: "पिन गिराया गया",
    navHere: "यहाँ नेविगेट करें",
    tapMap: "पिन गिराने के लिए मैप पर टैप करें"
  },
  'ta-IN': {
    appTitle: "LifeGuard AI",
    home: "முகப்பு",
    firstAid: "முதலுதவி",
    nearby: "அருகில்",
    profile: "சுயவிவரம்",
    welcome: "வணக்கம்",
    emergencyMode: "அவசர நிலை பயன்முறை செயலில் உள்ளது. உதவி ஒரு தட்டல் தொலைவில்.",
    blood: "இரத்தம்",
    contact: "தொடர்பு",
    sosTitle: "அவசர SOS",
    ambulance: "ஆம்புலன்ஸ்",
    police: "காவல்துறை",
    fire: "தீயணைப்பு",
    family: "குடும்பம்",
    quickAssist: "விரைவான உதவி",
    firstAidTitle: "முதலுதவி AI",
    firstAidDesc: "CPR, தீக்காயங்கள் மற்றும் வெட்டுக்களுக்கு உடனடி வழிகாட்டுதல் பெறுங்கள்.",
    findHospitals: "மருத்துவமனைகளைத் தேடுங்கள்",
    findHospitalsDesc: "அருகிலுள்ள மருத்துவ மையங்களை உடனடியாகக் கண்டறியவும்.",
    chatPlaceholder: "அவசர நிலையை விவரிக்கவும்...",
    listen: "கேளுங்கள்",
    stop: "நிறுத்து",
    send: "அனுப்பு",
    medicalId: "மருத்துவ அடையாள அட்டை",
    save: "சேமி",
    edit: "திருத்து",
    medicalCond: "மருத்துவ நிலைகள்",
    currentLoc: "தற்போதைய இருப்பிடம்",
    update: "புதுப்பி",
    updating: "புதுப்பிக்கப்படுகிறது...",
    settings: "அமைப்புகள்",
    language: "மொழி",
    privacy: "தனியுரிமைக் கொள்கை",
    mapApp: "Google Maps பயன்படுத்தவும்",
    navMap: "வழிசெலுத்தலைப் பெறவும்",
    open: "திற",
    getDir: "திசைகள்",
    locating: "கண்டறிகிறது...",
    signIn: "உள்நுழைய",
    createAccount: "கணக்கை உருவாக்கவும்",
    sources: "ஆதாரங்கள்:",
    nearbyCenters: "அருகிலுள்ள மருத்துவ மையங்கள்",
    chatHistory: "அரட்டை வரலாறு",
    noHistory: "அரட்டை வரலாறு இல்லை.",
    yourQuery: "நீங்கள் கேட்டது",
    dropPin: "பின் போடப்பட்டது",
    navHere: "இங்கே செல்லவும்",
    tapMap: "பின் செய்ய வரைபடத்தில் தட்டவும்"
  }
};

export const t = (key: string, lang: string = 'en-US'): string => {
  return TRANSLATIONS[lang]?.[key] || TRANSLATIONS['en-US'][key] || key;
};